[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_biu = "AuDZCMRLBovvSc3214tq4tPAnn16TtgMXE1dFSMkvRoe"

[programs.devnet]
token_biu = "HkfLotTYqtbBR3wjyMZcojaiQuSpFGaWFYCnXQQeaT9Y"

[programs.mainnet]
token_biu = "7PASEEKtEGDeEpQg3CVCb37eKBSWAZeXh7jsXxkvaA8t"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "new-keypair.json"

[test]
startup_wait = 10000

[test.validator]
args = ["--enable-cpi-and-pda-with-clock-sysvar-write", "--bpf-program", "WaRpT1mMYNtGMhMGpcXUYVauQDFNRJrbPbbELGcapsw=clocksetter.so", "--warp-slot", "1000"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
